[2022-11-22T14:47:16.287+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: python_dependences.task1 manual__2022-11-22T14:47:14.551150+00:00 [queued]>
[2022-11-22T14:47:16.300+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: python_dependences.task1 manual__2022-11-22T14:47:14.551150+00:00 [queued]>
[2022-11-22T14:47:16.302+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T14:47:16.304+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-11-22T14:47:16.305+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T14:47:16.323+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): task1> on 2022-11-22 14:47:14.551150+00:00
[2022-11-22T14:47:16.332+0000] {standard_task_runner.py:55} INFO - Started process 74 to run task
[2022-11-22T14:47:16.337+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'python_dependences', 'task1', 'manual__2022-11-22T14:47:14.551150+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_test_with_python_dependence.py', '--cfg-path', '/tmp/tmpbboac23e']
[2022-11-22T14:47:16.339+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask task1
[2022-11-22T14:47:16.408+0000] {task_command.py:376} INFO - Running <TaskInstance: python_dependences.task1 manual__2022-11-22T14:47:14.551150+00:00 [running]> on host 10ff3b602703
[2022-11-22T14:47:16.468+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=klein
AIRFLOW_CTX_DAG_ID=python_dependences
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T14:47:14.551150+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T14:47:14.551150+00:00
[2022-11-22T14:47:16.472+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_test_with_python_dependence.py", line 8, in get_version
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2022-11-22T14:47:16.483+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=python_dependences, task_id=task1, execution_date=20221122T144714, start_date=20221122T144716, end_date=20221122T144716
[2022-11-22T14:47:16.492+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task task1 (No module named 'sklearn'; 74)
[2022-11-22T14:47:16.509+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-22T14:47:16.531+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
