[2022-11-24T22:43:20.267+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: py_name.print_name scheduled__2022-11-23T00:00:00+00:00 [queued]>
[2022-11-24T22:43:20.277+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: py_name.print_name scheduled__2022-11-23T00:00:00+00:00 [queued]>
[2022-11-24T22:43:20.279+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-24T22:43:20.280+0000] {taskinstance.py:1363} INFO - Starting attempt 3 of 3
[2022-11-24T22:43:20.281+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-24T22:43:20.295+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): print_name> on 2022-11-23 00:00:00+00:00
[2022-11-24T22:43:20.302+0000] {standard_task_runner.py:55} INFO - Started process 61 to run task
[2022-11-24T22:43:20.312+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'py_name', 'print_name', 'scheduled__2022-11-23T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_name.py', '--cfg-path', '/tmp/tmp1a5dfwv5']
[2022-11-24T22:43:20.314+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask print_name
[2022-11-24T22:43:20.334+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-24T22:43:20.391+0000] {task_command.py:376} INFO - Running <TaskInstance: py_name.print_name scheduled__2022-11-23T00:00:00+00:00 [running]> on host 89ee96b17a7e
[2022-11-24T22:43:20.457+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=klein
AIRFLOW_CTX_DAG_ID=py_name
AIRFLOW_CTX_TASK_ID=print_name
AIRFLOW_CTX_EXECUTION_DATE=2022-11-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-23T00:00:00+00:00
[2022-11-24T22:43:20.459+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: print_name_settings() takes 1 positional argument but 5 were given
[2022-11-24T22:43:20.469+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=py_name, task_id=print_name, execution_date=20221123T000000, start_date=20221124T224320, end_date=20221124T224320
[2022-11-24T22:43:20.480+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 37 for task print_name (print_name_settings() takes 1 positional argument but 5 were given; 61)
[2022-11-24T22:43:20.525+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-24T22:43:20.556+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
