[2022-11-24T14:37:21.072+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: postgres_operators.create_table manual__2022-11-24T14:34:55.783777+00:00 [queued]>
[2022-11-24T14:37:21.083+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: postgres_operators.create_table manual__2022-11-24T14:34:55.783777+00:00 [queued]>
[2022-11-24T14:37:21.084+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-24T14:37:21.085+0000] {taskinstance.py:1363} INFO - Starting attempt 3 of 3
[2022-11-24T14:37:21.086+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-24T14:37:21.098+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-24 14:34:55.783777+00:00
[2022-11-24T14:37:21.104+0000] {standard_task_runner.py:55} INFO - Started process 57 to run task
[2022-11-24T14:37:21.108+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'postgres_operators', 'create_table', 'manual__2022-11-24T14:34:55.783777+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/DBconnection.py', '--cfg-path', '/tmp/tmpf770mdir']
[2022-11-24T14:37:21.110+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask create_table
[2022-11-24T14:37:21.177+0000] {task_command.py:376} INFO - Running <TaskInstance: postgres_operators.create_table manual__2022-11-24T14:34:55.783777+00:00 [running]> on host 89ee96b17a7e
[2022-11-24T14:37:21.246+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=klein
AIRFLOW_CTX_DAG_ID=postgres_operators
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-24T14:34:55.783777+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-24T14:34:55.783777+00:00
[2022-11-24T14:37:21.261+0000] {base.py:71} INFO - Using connection ID 'DB_localhost' for task execution.
[2022-11-24T14:37:31.279+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 115, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2022-11-24T14:37:31.318+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=postgres_operators, task_id=create_table, execution_date=20221124T143455, start_date=20221124T143721, end_date=20221124T143731
[2022-11-24T14:37:31.343+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task create_table (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 57)
[2022-11-24T14:37:31.398+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-24T14:37:31.423+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
