[2022-11-25T09:40:42.738+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Postgres_Data.select_data manual__2022-11-25T09:38:38.548187+00:00 [queued]>
[2022-11-25T09:40:42.750+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Postgres_Data.select_data manual__2022-11-25T09:38:38.548187+00:00 [queued]>
[2022-11-25T09:40:42.751+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-25T09:40:42.752+0000] {taskinstance.py:1363} INFO - Starting attempt 3 of 3
[2022-11-25T09:40:42.753+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-25T09:40:42.767+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): select_data> on 2022-11-25 09:38:38.548187+00:00
[2022-11-25T09:40:42.783+0000] {standard_task_runner.py:55} INFO - Started process 70 to run task
[2022-11-25T09:40:42.792+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Postgres_Data', 'select_data', 'manual__2022-11-25T09:38:38.548187+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/ConnectionTable.py', '--cfg-path', '/tmp/tmpk6yk7_af']
[2022-11-25T09:40:42.796+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask select_data
[2022-11-25T09:40:42.883+0000] {task_command.py:376} INFO - Running <TaskInstance: Postgres_Data.select_data manual__2022-11-25T09:38:38.548187+00:00 [running]> on host 89ee96b17a7e
[2022-11-25T09:40:42.945+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=klein
AIRFLOW_CTX_DAG_ID=Postgres_Data
AIRFLOW_CTX_TASK_ID=select_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T09:38:38.548187+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-25T09:38:38.548187+00:00
[2022-11-25T09:40:42.955+0000] {base.py:71} INFO - Using connection ID 'DB_ytb' for task execution.
[2022-11-25T09:40:42.975+0000] {sql.py:315} INFO - Running statement: 
        SELECT * FROM COMMENTS
        WHERE textDisplay LIKE "%merci%"
        , parameters: None
[2022-11-25T09:40:42.982+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "%merci%" does not exist
LINE 3:         WHERE textDisplay LIKE "%merci%"
                                       ^

[2022-11-25T09:40:42.993+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Postgres_Data, task_id=select_data, execution_date=20221125T093838, start_date=20221125T094042, end_date=20221125T094042
[2022-11-25T09:40:43.010+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 52 for task select_data (column "%merci%" does not exist
LINE 3:         WHERE textDisplay LIKE "%merci%"
                                       ^
; 70)
[2022-11-25T09:40:43.044+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-25T09:40:43.067+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
