[2022-11-25T09:38:41.026+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Postgres_Data.select_data manual__2022-11-25T09:38:38.548187+00:00 [queued]>
[2022-11-25T09:38:41.037+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Postgres_Data.select_data manual__2022-11-25T09:38:38.548187+00:00 [queued]>
[2022-11-25T09:38:41.038+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-25T09:38:41.039+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-11-25T09:38:41.040+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-25T09:38:41.052+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): select_data> on 2022-11-25 09:38:38.548187+00:00
[2022-11-25T09:38:41.058+0000] {standard_task_runner.py:55} INFO - Started process 66 to run task
[2022-11-25T09:38:41.063+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Postgres_Data', 'select_data', 'manual__2022-11-25T09:38:38.548187+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/ConnectionTable.py', '--cfg-path', '/tmp/tmpmpmfct0k']
[2022-11-25T09:38:41.065+0000] {standard_task_runner.py:83} INFO - Job 50: Subtask select_data
[2022-11-25T09:38:41.125+0000] {task_command.py:376} INFO - Running <TaskInstance: Postgres_Data.select_data manual__2022-11-25T09:38:38.548187+00:00 [running]> on host 89ee96b17a7e
[2022-11-25T09:38:41.190+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=klein
AIRFLOW_CTX_DAG_ID=Postgres_Data
AIRFLOW_CTX_TASK_ID=select_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T09:38:38.548187+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-25T09:38:38.548187+00:00
[2022-11-25T09:38:41.201+0000] {base.py:71} INFO - Using connection ID 'DB_ytb' for task execution.
[2022-11-25T09:38:41.217+0000] {sql.py:315} INFO - Running statement: 
        SELECT * FROM COMMENTS
        WHERE textDisplay LIKE "%merci%"
        , parameters: None
[2022-11-25T09:38:41.226+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "%merci%" does not exist
LINE 3:         WHERE textDisplay LIKE "%merci%"
                                       ^

[2022-11-25T09:38:41.241+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=Postgres_Data, task_id=select_data, execution_date=20221125T093838, start_date=20221125T093841, end_date=20221125T093841
[2022-11-25T09:38:41.261+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 50 for task select_data (column "%merci%" does not exist
LINE 3:         WHERE textDisplay LIKE "%merci%"
                                       ^
; 66)
[2022-11-25T09:38:41.319+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-25T09:38:41.342+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
