[2022-11-25T09:43:39.391+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Postgres_Data.select_data manual__2022-11-25T09:41:34.598316+00:00 [queued]>
[2022-11-25T09:43:39.405+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Postgres_Data.select_data manual__2022-11-25T09:41:34.598316+00:00 [queued]>
[2022-11-25T09:43:39.407+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-25T09:43:39.409+0000] {taskinstance.py:1363} INFO - Starting attempt 3 of 3
[2022-11-25T09:43:39.411+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-25T09:43:39.428+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): select_data> on 2022-11-25 09:41:34.598316+00:00
[2022-11-25T09:43:39.437+0000] {standard_task_runner.py:55} INFO - Started process 78 to run task
[2022-11-25T09:43:39.443+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Postgres_Data', 'select_data', 'manual__2022-11-25T09:41:34.598316+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/ConnectionTable.py', '--cfg-path', '/tmp/tmprxodyi1c']
[2022-11-25T09:43:39.446+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask select_data
[2022-11-25T09:43:39.535+0000] {task_command.py:376} INFO - Running <TaskInstance: Postgres_Data.select_data manual__2022-11-25T09:41:34.598316+00:00 [running]> on host 89ee96b17a7e
[2022-11-25T09:43:39.626+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=klein
AIRFLOW_CTX_DAG_ID=Postgres_Data
AIRFLOW_CTX_TASK_ID=select_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T09:41:34.598316+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-25T09:41:34.598316+00:00
[2022-11-25T09:43:39.640+0000] {base.py:71} INFO - Using connection ID 'DB_ytb' for task execution.
[2022-11-25T09:43:39.666+0000] {sql.py:315} INFO - Running statement: 
        SELECT * FROM COMMENTS
        WHERE textDisplay LIKE "%merci%";
        , parameters: None
[2022-11-25T09:43:39.674+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "%merci%" does not exist
LINE 3:         WHERE textDisplay LIKE "%merci%";
                                       ^

[2022-11-25T09:43:39.694+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=Postgres_Data, task_id=select_data, execution_date=20221125T094134, start_date=20221125T094339, end_date=20221125T094339
[2022-11-25T09:43:39.709+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task select_data (column "%merci%" does not exist
LINE 3:         WHERE textDisplay LIKE "%merci%";
                                       ^
; 78)
[2022-11-25T09:43:39.740+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-25T09:43:39.766+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
