[2022-11-22T14:44:17.940+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: python_dependences.task1 manual__2022-11-22T14:44:16.782354+00:00 [queued]>
[2022-11-22T14:44:17.951+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: python_dependences.task1 manual__2022-11-22T14:44:16.782354+00:00 [queued]>
[2022-11-22T14:44:17.952+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T14:44:17.953+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 3
[2022-11-22T14:44:17.954+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-22T14:44:17.969+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): task1> on 2022-11-22 14:44:16.782354+00:00
[2022-11-22T14:44:17.979+0000] {standard_task_runner.py:55} INFO - Started process 62 to run task
[2022-11-22T14:44:17.984+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'python_dependences', 'task1', 'manual__2022-11-22T14:44:16.782354+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_test_with_python_dependence.py', '--cfg-path', '/tmp/tmpson42flx']
[2022-11-22T14:44:17.985+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask task1
[2022-11-22T14:44:18.063+0000] {task_command.py:376} INFO - Running <TaskInstance: python_dependences.task1 manual__2022-11-22T14:44:16.782354+00:00 [running]> on host 10ff3b602703
[2022-11-22T14:44:18.140+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=klein
AIRFLOW_CTX_DAG_ID=python_dependences
AIRFLOW_CTX_TASK_ID=task1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T14:44:16.782354+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T14:44:16.782354+00:00
[2022-11-22T14:44:18.146+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_test_with_python_dependence.py", line 8, in get_version
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2022-11-22T14:44:18.161+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=python_dependences, task_id=task1, execution_date=20221122T144416, start_date=20221122T144417, end_date=20221122T144418
[2022-11-22T14:44:18.185+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task task1 (No module named 'sklearn'; 62)
[2022-11-22T14:44:18.238+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-22T14:44:18.268+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
